namespace Brawler.CustomInput
{
    public enum JoyStickAxises
    {
        Joystick1RightHorizontal,
        Joystick1RightVertical,
        Joystick1LeftHorizontal,
        Joystick1LeftVertical,
        Joystick1LeftTrigger,
        Joystick1RightTrigger,
        Joystick1DpadHorizontal,
        Joystick1DpadVertical,
        Joystick2RightHorizontal,
        Joystick2RightVertical,
        Joystick2LeftHorizontal,
        Joystick2LeftVertical,
        Joystick2LeftTrigger,
        Joystick2RightTrigger,
        Joystick2DpadHorizontal,
        Joystick2DpadVertical,
        Joystick3RightHorizontal,
        Joystick3RightVertical,
        Joystick3LeftHorizontal,
        Joystick3LeftVertical,
        Joystick3LeftTrigger,
        Joystick3RightTrigger,
        Joystick3DpadHorizontal,
        Joystick3DpadVertical,
        Joystick4RightHorizontal,
        Joystick4RightVertical,
        Joystick4LeftHorizontal,
        Joystick4LeftVertical,
        Joystick4LeftTrigger,
        Joystick4RightTrigger,
        Joystick4DpadHorizontal,
        Joystick4DpadVertical
    }
}